import { readdirSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

// Define __dirname for ES module
const __dirname = dirname(fileURLToPath(import.meta.url));

// Define the directory containing the images
const imagesDir = join(__dirname, "../assets"); // Use ../assets to go up to the assets directory from scripts

// Read all files in the directory
const files = readdirSync(imagesDir);

// Filter to include only .png files
const imageFiles = files.filter((file) => file.endsWith(".png"));

// Generate import statements and array entries for each image
const imports = imageFiles
  .map((file, index) => {
    const variableName = file.replace(".png", ""); // Remove .png to create a unique variable name
    return `import ${variableName} from './${file}';`;
  })
  .join("\n");

const imagesArray = imageFiles
  .map((file) => {
    const nameWithoutExtension = file.replace(".png", "");
    return `{ name: '${nameWithoutExtension}', src: ${nameWithoutExtension} }`;
  })
  .join(",\n  ");

// Create the content for the teamImages.js file
const fileContent = `
// This file is auto-generated by generateTeamImgIndex.mjs

${imports}

const teamImages = [
  ${imagesArray}
];

export default teamImages;
`;

// Write the content to assets/index.js
writeFileSync(join(imagesDir, "index.js"), fileContent);

console.log("index.js file generated successfully in assets directory.");
