const ZOOM_CARDS = Object.entries({
  o: "Holiday",
  p: "Holiday",
  q: "Holiday",
  r: "Holiday",
  s: "Holiday",
  t: "Holiday",
  u: "Holiday",
  v: "Holiday",
  w: "Holiday",
  x: "Holiday",
  y: "Holiday",
  z: "Holiday",
  aa: "Holiday",
  ab: "Holiday",
  ac: "Holiday",
  ad: "Holiday",
  a: "Serenity",
  b: "Spectrum Street",
  c: "Color Canyon",
  d: "Illuminate",
  e: "Ideas Poppin",
  f: "Digital Worlds",
  g: "In the Zone",
  h: "Mountain Mist",
  i: "Desert Night",
  j: "A Calm Coast",
  k: "A Peaceful Place",
  l: "Odyssey",
  m: "Interstellar",
  n: "Ethereal",
});

export default ZOOM_CARDS;
